import { StyleSheet } from "react-native";
import { Colors } from "../../../theme/colors";

export const adminResourceSectionStyles = StyleSheet.create({
  stack: {
    gap: 14,
  },
  summaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  summaryCard: {
    flexGrow: 1,
    minWidth: "47%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    padding: 14,
    gap: 6,
  },
  summaryLabel: {
    color: Colors.subtleText,
    fontSize: 12,
    fontWeight: "600",
  },
  summaryValue: {
    color: Colors.text,
    fontSize: 22,
    fontWeight: "800",
  },
  sectionCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    overflow: "hidden",
  },
  sectionHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  sectionTitle: {
    color: Colors.text,
    fontSize: 15,
    fontWeight: "800",
  },
  sectionMuted: {
    color: Colors.subtleText,
    fontSize: 12,
    fontWeight: "600",
  },
  inlineAction: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: Colors.primarySoft,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  inlineActionMuted: {
    backgroundColor: Colors.input,
  },
  inlineActionDanger: {
    backgroundColor: "rgba(239, 68, 68, 0.12)",
  },
  inlineActionText: {
    color: Colors.primary,
    fontSize: 12,
    fontWeight: "700",
  },
  inlineActionTextMuted: {
    color: Colors.text,
    fontSize: 12,
    fontWeight: "700",
  },
  inlineActionTextDanger: {
    color: Colors.danger,
    fontSize: 12,
    fontWeight: "700",
  },
  emptyText: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    color: Colors.subtleText,
    fontSize: 13,
    lineHeight: 20,
  },
  resourceActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  centerState: {
    minHeight: 180,
    alignItems: "center",
    justifyContent: "center",
  },
  list: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    gap: 10,
  },
  memberRow: {
    gap: 12,
    padding: 12,
    borderRadius: 16,
    backgroundColor: Colors.input,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  memberMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  memberAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: Colors.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  memberAvatarImage: {
    width: "100%",
    height: "100%",
  },
  memberAvatarLetter: {
    color: Colors.primary,
    fontSize: 15,
    fontWeight: "800",
  },
  memberCopy: {
    flex: 1,
    gap: 2,
  },
  memberName: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: "700",
  },
  memberSub: {
    color: Colors.subtleText,
    fontSize: 12,
    lineHeight: 18,
  },
  attendanceActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  statusChip: {
    minHeight: 32,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  statusChipActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primarySoft,
  },
  statusChipText: {
    color: Colors.subtleText,
    fontSize: 12,
    fontWeight: "700",
  },
  statusChipTextActive: {
    color: Colors.primary,
  },
  studentCard: {
    gap: 12,
    padding: 12,
    borderRadius: 16,
    backgroundColor: Colors.input,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  oralEditor: {
    gap: 10,
  },
  input: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    color: Colors.text,
    paddingHorizontal: 12,
    fontSize: 14,
  },
  textarea: {
    minHeight: 84,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    color: Colors.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    lineHeight: 20,
  },
  oralSummary: {
    gap: 4,
  },
  oralSummaryTitle: {
    color: Colors.text,
    fontSize: 13,
    fontWeight: "700",
  },
  oralSummaryValue: {
    color: Colors.primary,
    fontWeight: "800",
  },
  extraPill: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: Colors.input,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  extraPillText: {
    color: Colors.subtleText,
    fontSize: 11,
    fontWeight: "700",
  },
  materialsList: {
    paddingBottom: 14,
    gap: 10,
  },
  materialCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 16,
    backgroundColor: Colors.input,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  materialMeta: {
    flex: 1,
    gap: 3,
  },
  materialName: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: "700",
  },
  materialSub: {
    color: Colors.subtleText,
    fontSize: 12,
  },
  materialActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  materialIconButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  resourceList: {
    paddingBottom: 14,
    gap: 10,
  },
  resourceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 14,
    backgroundColor: Colors.input,
  },
  resourceCopy: {
    flex: 1,
    gap: 3,
  },
  resourceTitle: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: "700",
  },
  resourceMeta: {
    color: Colors.subtleText,
    fontSize: 12,
  },
  resourceButton: {
    minWidth: 72,
    height: 34,
    borderRadius: 999,
    paddingHorizontal: 14,
    backgroundColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  resourceButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  progressBadgeText: {
    color: Colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  rowIconButton: {
    width: 28,
    height: 28,
    borderRadius: 10,
    backgroundColor: Colors.input,
    alignItems: "center",
    justifyContent: "center",
  },
  homeworkCard: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: Colors.input,
    gap: 10,
  },
  homeworkDescription: {
    color: Colors.mutedText,
    fontSize: 13,
    lineHeight: 18,
  },
});
